### ISSUE TITLE
[power_regul] Diode D1 reverse

### ISSUE THREAD

**Issue by Salamandar** [PhenixRobotik/theyseemerolling-elec#1]
La diode D1 reverse sert, je suppose, à absorber le courant en cas d'alim inversée.
Si c'est le cas, pourquoi ne pas mettre (aussi ?) une diode en directe entre power_input et power ?

**Comment by 42Max42** [comment]
C'est ça, et quand il y a inversion le fusible doit sauter (attention au dimensionnement de la diode par rapport au fusible). Si on ne met pas la diode en inverse, c'est pour éviter de faire passer toute la puissance dans cette diode, et donc de chauffer et perdre de l'énergie inutilement.

**Comment by Salamandar** [comment]
> Si on ne met pas la diode en inverse

Tu voulais dire directe ?

En tout cas je comprends, donc je retire ce que j'ai dit.

**Comment by 42Max42** [comment]
Oui
