### ISSUE TITLE
[power_regul] Elec_input = 7V, regul 5v

### ISSUE THREAD

**Issue by Salamandar** [PhenixRobotik/theyseemerolling-elec#2]
Ce qu'il se passe sur le bus n'est pas contrôlé par la board (interférences, proximité des câbles de puissance, etc), il faudrait donc un régul 5v sur la board.

Cela "oblige" à fournir par le bus plus de 5v (parce que le régul sera certainement un step down). Certaines équipes se fixent sur 7.5v. Sur notre aspirateur robot je crois que c'était 7V. Mais dans le détail, on s'en fout : Il faut un régul 5v (en parallèle ou en amont du régul 3v3 ?).

**Comment by 42Max42** [comment]
en amont avec de LOD (faible chute pour le 3.3V), on perd moins de puissance, après oui j'hésitais entre propager un +5V qui sert à tout les processeurs et capteurs, avec éventuellement une autre régul à +3.3V, ou propager une tension supérieure à 5V (au moins 6V), puis une régul à 5V par carte. Après 7,4V c'est parceque c'est une tension de lipo 2s, donc on est pas obligé de ce fixer sur cette tension, il faut tirer le courant sur toutes les cellules en même temps c'est mieux.

Mais pourquoi il faut pas que le +5V soit le même distribué à chaque carte? Avec des capas de découplage ça doit être bon?

**Comment by Salamandar** [comment]
> Mais pourquoi il faut pas que le +5V soit le même distribué à chaque carte? Avec des capas de découplage ça doit être bon?

C'est aussi : On va tirer du courant, donc il y aura des chutes de courant dans câblage + connecteurs, forcément. Donc il *faut* un régul (oui j'ai pas dit ça dans le message original). Et si on veut mettre un régul, il faut comme tu le dis au moins 6V ;)
Et je disais step-down en opposition à step-up, pas en opposition à LDO. En effet pour l'électronique, mieux vaudra un low drop qui a une efficacité meilleure.

**Comment by 42Max42** [comment]
Après sur le +5V avec les capteurs et les f3 (Raspberry sur un rail à part quand même), je suis pas convaincu qu'on tire un courrant assez fort pour engendrer une chute significative, mais en même temps c'est pas compliqué de rajouter un régul pour le +5V

**Comment by Salamandar** [comment]
> Raspberry sur un rail à part quand même

Ah putain t'as raison, il faudra prévoir ça sur la carte alim (genre une sortie usb "standard").

> je suis pas convaincu qu'on tire un courrant assez fort pour engendrer une chute significative

Oublie pas que c'est ça qui va alimenter la majorité des capteurs (qui peuvent tirer un petit peu par pics) et actionneurs (pour les servos, ça se discute, certes, mais mieux vaut qu'ils ne soient pas influencés par l'alim moteur, et ils sont forcément sur la même masse que le MCU qui les contrôle).

**Comment by 42Max42** [comment]
> (pour les servos, ça se discute, certes, mais mieux vaut qu'ils ne soient pas influencés par l'alim moteur, et ils sont forcément sur la même masse que le MCU qui les contrôle).

Tu mets pas des servos sur l'alim +5V des capteurs. Mais il c'est vrai il faudrait des régulateurs pour le +5V sur les boards.

**Comment by Salamandar** [comment]
D'où l'idée que ça se discute. Mon avis est :
* On va pas les alimenter par l'alim moteurs
* On va pas multiplier les alims en mode yolo
Après t'as raison que utiliser l'alim des capteurs n'est pas très propre.

**Comment by 42Max42** [comment]
Donc du coup:

- Une alim 7-8V pour les capteurs et f3

- Une alim +5V bourir pour la raspberry

- l'alim séparée des moteurs
